spring:
  application:
    name: "eurekaserver"

  config:
    import: "optional:configserver:http://localhost:8071/"


management:
  endpoints:
    web:
      exposure:
        include: "*"

  #   Readyness and liveness  prove configuration
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
