
build:
  version: 2.0

accounts:
  message: "Welcome to easyBamk Accounts fron qa env."
  contactsDetails:
    name: "Amit g"
    email: "jNQKg@example.com"
  onCallSupport:
    - 1234567890
    - 1234567891