server:
  port: 8071

spring:
  application:
    name: "configserver"



  profiles:
    active: native

  cloud:
    config:
      server:
        native:
#          search-locations: "file:///home//amit//udmey_microservices//config"
        search-locations: "classpath:/config"
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

  rabbitmq:
    host: "rabbitmq"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

#   Readyness and liveness  prove configuration
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

